version: '3'

services:
  db:
    image: f615a9bed8ff
    container_name: DB_TEST
    restart: unless-stopped
    environment:
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWD=${MYSQL_PASSWD}
    - MYSQL_HOST=${MYSQL_HOST}
    - MYSQL_PORT=${MYSQL_PORT}
    - MYSQL_DB=${MYSQL_DB}
    ports:
    - 8048:8048/tcp